--- #YAML:1.0
name:               Messages
version:            0.01
abstract:           Module abstract (<= 44 characters) goes here
author:
    - Byron Austin (byronx.l.austin@intel.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Simple:  0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
